// jenkins file for spa-env-server

def APP_NAME = 'spa-env-server'
def APP_VERSION = 'master'
def TAG_NAMES = ['dev', 'test', 'prod']

def BUILD_CONFIG = APP_NAME 
def IMAGESTREAM_NAME = APP_NAME

node {
    stage('build') {
       echo "Building: " + BUILD_CONFIG
       // openshiftBuild bldCfg: BUILD_CONFIG, showBuildLogs: 'true'
       // oc run-build BUILD_CONFIG --follow
       IMAGE_HASH = sh (
           script: """oc get istag ${IMAGESTREAM_NAME}:latest -o template --template=\"{{.image.dockerImageReference}}\"|awk -F \":\" \'{print \$3}\'""", returnStdout: true).trim()
       echo ">> IMAGE_HASH: $IMAGE_HASH"
    }

    stage('deploy-' + TAG_NAMES[0]) {
       echo "Deploying to: " + TAG_NAMES[0]
       echo "Deploy to " + TAG_NAMES[0] + " " + IMAGESTREAM_NAME + ":" + "${IMAGE_HASH}"
       // openshiftTag destStream: IMAGESTREAM_NAME, verbose: 'true', destTag: TAG_NAMES[0], srcStream: IMAGESTREAM_NAME, srcTag: "${IMAGE_HASH}"
       // oc tag IMAGESTREAM_NAME + ":" + "${IMAGE_HASH}" IMAGESTREAM_NAME + ":" + TAG_NAMES[0]
    }
}

