export const SupportDocumentTypes = {
  CanadianBirthCertificate: 'Canadian birth certificate',
  CanadianPassport: 'Canadian passport',
  CanadianCitizenCard: 'Canadian Citizenship Card or Certificate (front and back)',
  DriversLicense: 'BC Driver\'s License',
  RecordOfLanding: 'Record of Landing',
  PermanentResidentCard: 'Permanent resident card (front and back)',
  PermanentResidentConfirmation: 'Confirmation of Permanent Residence',
  WorkPermit: 'Work permit / CUAET',
  StudyPermit: 'Study permit',
  VisitorVisa: 'Visitor permit',
  PassportWithDiplomaticFoil: 'Passport with diplomatic foil',
  MarriageCertificate: 'Marriage certificate',
  ChangeOfNameCertificate: 'Name change certificate / Certificate of name change',
  ReligiousWorker: 'Religious worker',
  NoticeOfDecision: 'Notice of decision',
  DiplomaticPassportAcceptance: 'Diplomatic passport acceptance',
  WorkInCanadaAcceptance: 'Work in Canada acceptance',
  DivorceDecree: 'Divorce decree',
  ChangeGenderAdultApplication:
    'Application for change of gender designation (adult)',
  ChangeGenderMinorApplication:
    'Application for change of gender designation (minor)',
  ChangeGenderPhysicianConfirmation:
    'Physician\'s or psychologist confirmation of change of gender designation form',
  ChangeGenderDocs: 'Change of gender designation, request for waiver of parental consent',
  ParentalConsentWaiver:
    'Request for waiver of parental consent (minor) (for under 19 years)',
  SeparationAgreement: 'Separation agreement',
  NotarizedStatementOrAffidavit: 'Notarized statement or affidavit',
  Other: 'Other',
};

export const SupportDocumentSamples = {
  [SupportDocumentTypes.CanadianBirthCertificate]: 'canadian_birth_certs.jpg',
  [SupportDocumentTypes.CanadianPassport]: 'canadian_passport.jpg',
  [SupportDocumentTypes.CanadianCitizenCard]: 'canadian_cit_card_cert.jpg',
  [SupportDocumentTypes.DriversLicense]: 'bc_drivers_license.jpg',
  [SupportDocumentTypes.RecordOfLanding]: 'record_of_landing.jpg',
  [SupportDocumentTypes.PermanentResidentCard]: 'perm_resident_card.jpg',
  [SupportDocumentTypes.PermanentResidentConfirmation]: 'perm_resident_conf.jpg',
  [SupportDocumentTypes.WorkPermit]: 'work_permit.png',
  [SupportDocumentTypes.StudyPermit]: 'study_permit.jpg',
  [SupportDocumentTypes.VisitorVisa]: 'visitor_permit.jpg',
  [SupportDocumentTypes.PassportWithDiplomaticFoil]: 'diplomatic_passport.jpg',
  [SupportDocumentTypes.MarriageCertificate]: 'marriage_cert.jpg',
  [SupportDocumentTypes.ChangeOfNameCertificate]: 'name_change_cert.jpg',
  [SupportDocumentTypes.ReligiousWorker]: 'visitor_permit.jpg',
  [SupportDocumentTypes.NoticeOfDecision]: '',
  [SupportDocumentTypes.DiplomaticPassportAcceptance]: '',
  [SupportDocumentTypes.WorkInCanadaAcceptance]: '',
  [SupportDocumentTypes.DivorceDecree]: '',
  [SupportDocumentTypes.ChangeGenderAdultApplication]: 'app_change_gender_adult.jpg',
  [SupportDocumentTypes.ChangeGenderMinorApplication]: 'app_change_gender_minor.jpg',
  [SupportDocumentTypes.ChangeGenderPhysicianConfirmation]: 'physician_conf_gender_designation.jpg',
  [SupportDocumentTypes.ChangeGenderDocs]: 'gender_forms.png',
  [SupportDocumentTypes.ParentalConsentWaiver]: '',
  [SupportDocumentTypes.SeparationAgreement]: 'separation_agreement.png',
  [SupportDocumentTypes.NotarizedStatementOrAffidavit]: '',
  [SupportDocumentTypes.Other]: '',
};
