export const SupportDocumentTypes = {
  CanadianBirthCertificate: 'Canadian birth certificate',
  CanadianPassport: 'Canadian passport',
  CanadianCitizenCard: 'Canadian citizenship card or certificate (front and back)',
  DriversLicense: 'BC Driver\'s License',
  RecordOfLanding: 'Record of Landing',
  PermanentResidentCard: 'Permanent Resident card (front and back)',
  PermanentResidentConfirmation: 'Confirmation of Permanent Residence',
  WorkPermit: 'Work permit / CUAET',
  StudyPermit: 'Study permit',
  VisitorVisa: 'Visitor permit',
  PassportWithDiplomaticFoil: 'Passport With Diplomatic Foil',
  MarriageCertificate: 'Marriage Certificate',
  ChangeOfNameCertificate: 'Name Change Certificate / Certificate of Name Change',
  ReligiousWorker: 'Religious Worker',
  NoticeOfDecision: 'Notice Of Decision',
  DiplomaticPassportAcceptance: 'Diplomatic Passport Acceptance',
  WorkInCanadaAcceptance: 'Work In Canada Acceptance',
  DivorceDecree: 'Divorce Decree',
  ChangeGenderAdultApplication:
    'Application for Change of Gender Designation (Adult)',
  ChangeGenderMinorApplication:
    'Application for Change of Gender Designation (Minor)',
  ChangeGenderPhysicianConfirmation:
    'Physician\'s or Psychologist Confirmation of Change of Gender Designation Form',
  ChangeGenderDocs: 'Change of Gender Designation, Request for Waiver of Parental Consent',
  ParentalConsentWaiver:
    'Request for Waiver of Parental Consent (minor) (for under 19 years)',
  SeparationAgreement: 'Separation Agreement',
  NotarizedStatementOrAffidavit: 'Notarized Statement Or Affidavit',
  Other: 'Other',
};

export const SupportDocumentSamples = {
  [SupportDocumentTypes.CanadianBirthCertificate]: 'canadian_birth_certs.jpg',
  [SupportDocumentTypes.CanadianPassport]: 'canadian_passport.jpg',
  [SupportDocumentTypes.CanadianCitizenCard]: 'canadian_cit_card_cert.jpg',
  [SupportDocumentTypes.DriversLicense]: 'bc_drivers_license.jpg',
  [SupportDocumentTypes.RecordOfLanding]: 'record_of_landing.jpg',
  [SupportDocumentTypes.PermanentResidentCard]: 'perm_resident_card.jpg',
  [SupportDocumentTypes.PermanentResidentConfirmation]: 'perm_resident_conf.jpg',
  [SupportDocumentTypes.WorkPermit]: 'work_permit.png',
  [SupportDocumentTypes.StudyPermit]: 'study_permit.jpg',
  [SupportDocumentTypes.VisitorVisa]: 'visitor_permit.jpg',
  [SupportDocumentTypes.PassportWithDiplomaticFoil]: 'diplomatic_passport.jpg',
  [SupportDocumentTypes.MarriageCertificate]: 'marriage_cert.jpg',
  [SupportDocumentTypes.ChangeOfNameCertificate]: 'name_change_cert.jpg',
  [SupportDocumentTypes.ReligiousWorker]: 'visitor_permit.jpg',
  [SupportDocumentTypes.NoticeOfDecision]: '',
  [SupportDocumentTypes.DiplomaticPassportAcceptance]: '',
  [SupportDocumentTypes.WorkInCanadaAcceptance]: '',
  [SupportDocumentTypes.DivorceDecree]: 'divorce_decree.jpg',
  [SupportDocumentTypes.ChangeGenderAdultApplication]: 'app_change_gender_adult.jpg',
  [SupportDocumentTypes.ChangeGenderMinorApplication]: 'app_change_gender_minor.jpg',
  [SupportDocumentTypes.ChangeGenderPhysicianConfirmation]: 'physician_conf_gender_designation.jpg',
  [SupportDocumentTypes.ChangeGenderDocs]: 'gender_forms.png',
  [SupportDocumentTypes.ParentalConsentWaiver]: '',
  [SupportDocumentTypes.SeparationAgreement]: 'separation_agreement.png',
  [SupportDocumentTypes.NotarizedStatementOrAffidavit]: '',
  [SupportDocumentTypes.Other]: '',
};
