# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Deployment template for the Platform Serices
      project registry.
    iconClass: icon-node
  name: msp-enrolment-web
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: msp-enrolment-web
    name: ${NAME}-to-api
  spec:
    host: "${NAME}-${NAMESPACE}.${CLUSTER_DOMAIN}"
    path: "/api"
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${API_SERVICE_NAME}
      weight: 100
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: msp-enrolment-web
    name: ${NAME}
  spec:
    path: ""
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: msp-enrolment-web
    name: ${NAME}
  spec:
    selector:
      deploymentconfig: ${NAME}
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: msp-enrolment-web
    name: ${NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${NAME}
          from:
            kind: ImageStreamTag
            name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
            namespace: ${SOURCE_IMAGE_NAMESPACE}
    replicas: 1
    selector:
      deploymentconfig: ${NAME}
    template:
      metadata:
        labels:
          app: msp-enrolment-web
          role: frontend
          deploymentconfig: ${NAME}
        name: ${NAME}
      spec:
        containers:
          - name: ${NAME}
            image: " "
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 180
              timeoutSeconds: 3
            ports:
              - containerPort: 8080
            env:
              - name: LOG_LEVEL
                value: debug
            resources:
              limits:
                cpu: 300m
                memory: 128Mi
              requests:
                cpu: 200m
                memory: 92Mi
            volumeMounts:
              - name: config-vol
                mountPath: /opt/app-root/src/nginx.conf
                subPath: nginx.conf
        volumes:
          - name: config-vol
            configMap:
              name: msp-web-config
parameters:
- description: |
    The name assigned to all of the objects defined in this template. You
    should keep this as default unless your know what your doing.
  displayName: Name
  name: NAME
  required: true
  value: msp-web
- description: |
    The namespace of the OpenShift project containing the imagestream for
    the application.
  displayName: Environment namespace
  name: NAMESPACE
  required: true
- description: |
    The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  required: true
- description: The name of the source image.
  displayName: Source Image Name
  name: SOURCE_IMAGE_NAME
  value: msp-web
  required: true
- description: The tag of the source image.
  displayName: Source Image Tag
  name: SOURCE_IMAGE_TAG
  required: true
- description: |
    The API service name is used to create a path based URL used by the Web
    to access the API. Its format will be common over all environments.
  displayName: API Service name
  name: API_SERVICE_NAME
  value: xxxx-api
  required: true
- description: |
    This is used to construct a path based route for the web to access the
    API.
  displayName: Cluster Domain Name
  name: CLUSTER_DOMAIN
  required: true
  value: apps.silver.devops.gov.bc.ca
