name: jha-web build
on:
  push:
    paths:
      - "jha/src/**/*.html"
      - "jha/src/**/*.ts"
      - "jha/src/**/*.js"
      - "jha/src/**/*.scss"
      - "jha/src/**/*.vue"
      - "jha/package*.json"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./jha
env:
  NAMESPACE: f0463d-tools
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test
      # - name: LINTing
      #   run: npm run test:lint
      # - name: OpenAPI Schema
      #   run: npm run test:schema
  build:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: "true"
  image-build:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Artifact Build
        env:
          BUILD_NAME: jha-web-artifact-build
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build ${BUILD_NAME} -n ${NAMESPACE} --follow'
      # Sleeping before tag to give time for image stream to settle.
      - name: Sleep before Artifact Deploy
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s
      - name: Artifact Deploy
        env:
          IMAGE_NAME: jha-web-artifacts
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
      - name: Image Build
        env:
          BUILD_NAME: jha-web-image-build
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build ${BUILD_NAME} -n ${NAMESPACE} --follow'
      # Sleeping before tag to give time for image stream to settle.
      - name: Sleep before Image Deploy
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s
      - name: Image Deploy
        env:
          IMAGE_NAME: jha-web
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
