name: npm audit workflow jha
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
defaults:
  run:
    working-directory: ./jha
jobs:
  scan:
    name: npm audit jha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: "12"
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.8.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ./jha
          issue_labels: vulnerability
          dedupe_issues: true
          production_flag: true
        name: run npm-audit-action
