name: spa-env-server deploy to prod
on: 
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
env:
  NAMESPACE: f0463d-tools
  IMAGE_NAME: spa-env-server
  SOURCE_IMAGE_TAG: test
  TARGET_IMAGE_TAG: prod
jobs:
  ocp-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "latest"
      - name: Log in to Openshift
        run: oc login --token=${{ secrets.OpenShiftToken }} --server=${{ secrets.OpenShiftServerURL}}
      - name: Deploy to Prod
        run: oc tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:${SOURCE_IMAGE_TAG} ${NAMESPACE}/${IMAGE_NAME}:${TARGET_IMAGE_TAG}